### ISSUE TITLE
Limiting selection of rows per column in Matrix

### ISSUE THREAD

**Issue by cwilligv** [antonmalko/shinyRadioMatrix#2]
Hi @antonmalko,

First of all, thanks for creating this shiny component, very helpful.

I'm using this component for a survey where each question has four sub-questions and each sub-question has only two options, MOST or LEAST. The thing is that I need to limit the column MOST to only one selection and column LEAST to one selection only as well.
Is there a way in your component to do that?

![question2](https://user-images.githubusercontent.com/11884925/207312960-ee8998a6-ac94-4944-a603-1240576c528f.png)

thanks in advance.

Christian.

**Comment by antonmalko** [comment]
Hi Christian, 

Just to check that I understand you correctly -- for your example, you want that only one of the four options can be marked as "most", and only one -- as "least", right?

If so, unfortunately you can't do it out of the box. Here are a few ideas which may help, but they are very quick, so you may need to play with them further. I might try to play with them myself, but I haven't looked at this code for some time and I can't promise it will happen soon.

A quick solution would be to just use several radio button groups, something like:

```
library(shiny)

ui <- fluidPage(
  fluidRow(
    column(2,
           tags$div(
                    tags$p("Question 1"),
                    tags$p("Enthusiastic"),
                    tags$p("Daring"),
                    tags$p("Diplomatic"),
                    tags$p("Satisfied"),
                    )
           ),
    column(1,
           radioButtons(inputId = "most", label = "Most",
                        choiceNames = c("","","",""),
                        choiceValues = c("a","b","c","d"))),
    column(1,
           radioButtons(inputId = "least", label = "Least",
                        choiceNames = c("","","",""),
                        choiceValues = c("a","b","c","d"))
           )
  )
)

server <- function(input, output, session) {
}

shinyApp(ui, server)
```

With this code the labels will be misaligned with radio buttons, but maybe this could be fixed with some CSS. 

A more involved way would be to modify the `generateRadioRow()` function in "inputRadioMatrix.R" file. Right now the function generates the radiobuttons in such a way that all buttons in a given row have the same "name" attribute in the HTML (the function uses the value from the `rowID` parameter). 

For your case, you might try to modify the function so that it gives the same name to radiobuttons *in the same column*. As far I remember, you would still need to generate the table row-by-row. Maybe if you change the following lines, this may give a starting point (but again, I haven't tried it):
	
+ line 37 -- change to `inputTag <- shiny::tags$input(type = "radio", name = name,`,
+ line 59 to -- change to `  shiny::tags$tr(name = name,`

**Comment by cwilligv** [comment]
Hi @antonmalko ,

Thank a lot for the reply. 

Yes, you understood my challenge correctly. I have tried your first suggestion but I'm still playing around a bit with the CSS to make it work (not really good at CSS tbh). 

Your second comment gave me an idea though. If you generateRadioRow() function gives the same "name" attribute to a row I might be able to provide exclusivity on the columns through javascript, as the value attribute is the column differentiator. I'll give it a try and come back.

Cheers.

**Comment by cwilligv** [comment]
Hey @antonmalko,

I've been able to restrict the column selection using Javascript, after doing some testing on fiddle ([https://jsfiddle.net/n2h5px1w/](https://jsfiddle.net/n2h5px1w/)) and looking at examples.

This is the javascript code I ended up with:
```
$(function() { 
  var col, el;
  $("input[type=radio]").click(function() {
    el = $(this);
    col = el.attr("value");
    $("input[value=" + col + "]").prop("checked", false);
    el.prop("checked", true);
  });
});
```
As you said the name of the rows give the matrix row exclusivity and the attribute value is the column, so I grabbed the value column previously clicked and unchecked the radio button.

I've integrated this into my shiny app with tags$script and worked perfectly as I wanted.

```
column_exclusivity_js <- '
$(function() {
			var col, el;
			$("input[type=radio]").click(function() {
			   el = $(this);
			   col = el.attr("value");
			   $("input[value=" + col + "]").prop("checked", false);
			   el.prop("checked", true);
			});
		});
'

ui <- fluidPage(tags$script(column_exclusivity_js),
                [radio_button_matrix_here]
)
```

Thanks for brainstorming ideas, it was really helpful.

Cheers.
